version: '3.8'

services:
  db:
    image: "mariadb"
    volumes:
      # In test mode, only deploy the test database for confidentiality issues
      - ./dump/test_dump.sql:/docker-entrypoint-initdb.d/QD.sql
      # - ./dump/QD.sql:/docker-entrypoint-initdb.d/QD.sql
    environment:
      MARIADB_ROOT_PASSWORD: root # change in production
      MYSQL_DATABASE: QD
    ports:
      - 3306:3306

  db-admin:
    image: "phpmyadmin"
    ports:
      - 8080:80